spring:
  application:
    name: spring-cloud-producer
    
server:
  #port: 9000
  #port: 8999
  port: 8998
  register:
    port1: 8000
    port2: 8001
    port3: 8002
    
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.register.port1}/eureka/